tags:
  - name: user
    description: user API

paths:
  # [POST] users/register
  /users/register:
    post:
      tags:
        - user
      summary: Register User
      parameters:
        - in: body
          name: body
          description: The user to register.
          schema:
            $ref: '#/definitions/user'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'


# definitions
definitions:
  user:
    type: object
    required:
      - email
    optional:
      - isAdmin
    properties:
      email:
        type: string
        description: user Email
      isAdmin:
        type: boolean
        description: user is admin

schemes:
 - https
 - http
