import calendarEventModel from "@models/calendarEvent.model";
import { CreateCalendarEventBackendDto, UpdateCalendarEventDto } from "@dtos/calendarEvent.dto";
import { CalendarEvent } from "@interfaces/calendarEvent.interface";
import { getStartOfCurrentYear } from "@utils/dayOff.helpers";
import userModel from "@models/user.model";

class CalendarEventService {
  public calendarEvent = calendarEventModel;
  public user = userModel;

  public async createCalendarEvent(data: CreateCalendarEventBackendDto): Promise<CalendarEvent> {
    return this.calendarEvent.create({ ...data, date: new Date(data.date) });
  }

  public async updateCalendarEvent(_id: string, data: Partial<UpdateCalendarEventDto>): Promise<CalendarEvent> {
    return this.calendarEvent.findOneAndUpdate({ _id }, { ...data, date: new Date(data.date) });
  }

  public async deleteCalendarEvent(_id: string) {
    return this.calendarEvent.findOneAndDelete({ _id });
  }

  public async getCalendarEventsForCurrentYear(): Promise<CalendarEvent[]> {
    const calendarEventsPromises = this.calendarEvent.find({
      $or: [
        {
          date: {
            $gte: getStartOfCurrentYear()
          }
        },
        {
          isRecurring: true
        }
      ]
    });

    const usersPromises: Promise<CalendarEvent[]> = this.user.find().then(users => users.flatMap(user => {
      return [{
        title: `${user.name} ${user.surname} Birthday`,
        _id: user._id,
        createdBy: "auto",
        autogenerated: true,
        description: `Happy birthday ${user.name} ${user.surname}!`,
        date: new Date(user.birthDate),
        isRecurring: true,
        isDayOff: false
      } as CalendarEvent,
        {
          title: `${user.name} ${user.surname} Anniversary`,
          _id: user._id,
          createdBy: "auto",
          autogenerated: true,
          description: `Happy anniversary ${user.name} ${user.surname}!`,
          date: new Date(user.workStartDate),
          isRecurring: true,
          isDayOff: false
        } as CalendarEvent
      ];
    }));

    return Promise.all([calendarEventsPromises, usersPromises])
      .then(([calendarEvents, users]) => [...calendarEvents, ...users]);
  }

  public async getHolidaysForCurrentYear(): Promise<CalendarEvent[]> {
    return this.calendarEvent.find({
      isDayOff: true,
      $or: [
        {
          date: {
            $gte: getStartOfCurrentYear()
          }
        },
        {
          isRecurring: true
        }
      ]
    });
  }

}

export default CalendarEventService;
